title: Hansen Sun
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "hansensun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hansen Sun # add your name
author-img: hansen.png # add your photo
about-author: Policy Analyst, Economist, Marathoner. Cal Golden Bear and Yale Bulldog. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hansensun # add your Github handle
social-linkedin: www.linkedin.com/in/hansensun
social-email: hansensun@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
